### ISSUE TITLE
Can't install : Could not read

### ISSUE THREAD

**Issue by jiljoel** [AbdulMuqsit/Starpack-Aleph#123]
**Describe the bug**
When I try to install the modpack, it rapidly says an error "Could not read" , and then all the curseforge app bug.
I've already unistalled et reinstalled curseforge, not effective.
I've already tried to install with "download" on curse website, not effective.

**Modpack Version**
- [1.16.5] StarPack Titan (Starpack-Titan-0.1.7.zip)

**To Reproduce**
1. Go to 'Curseforge'
2. Click on 'install' to install the modpack
3. Error on the beginning of the installation :  
Could not read
C:\Usersjiljo\AppData\Local\Temp\CF\zzrYNgABOkOpUUrt3BvjA\1.
zip as a zip file

4. i've around 10 mods installed, and played some 10 more, and that's the first one that dont want do install 

**Expected behavior**
I expect the modpack to install

**Screenshots**
![image](https://user-images.githubusercontent.com/96751884/147599552-cc9f780c-c493-47ef-a3a4-5269634e666d.png)

**Logs**
Dont have/dont know how to

**Comment by starmun-0010** [comment]
Can  you please follow the guide in the link to generate logs and send them? 
https://support.overwolf.com/en/support/solutions/articles/9000176827-how-to-get-your-overwolf-logs

Also, is it the same error or a different error, if you manually download the zip from curse website and import it in the launcher?

**Comment by jiljoel** [comment]
Hello,

Thanks for the reply, here is my Overwolf logs.

[OverwolfLogs_2021-12-28_23-49-44.zip](https://github.com/starmun-0010/starpack/files/7786632/OverwolfLogs_2021-12-28_23-49-44.zip)

I just tried to reinstall it before creating the logs.
Still crashes when it tries to unzip : 
![image](https://user-images.githubusercontent.com/96751884/147612821-4247039a-d256-474e-813b-0ef1ea36b450.png)

yes, its the same error.

**Comment by tomwolfgang** [comment]
Hey @jiljoel - I'm from the CurseForge team - could you please contact wolfgang#7086 on the CF discord channel?

https://discord.gg/6QG3msgq

Thanks

**Comment by jiljoel** [comment]
Hello tomwolfgang,

I tried to contact you from discord but apparently I can't
(asked you as friend, so maybe it would work, my id is "jiljoel")

![image](https://user-images.githubusercontent.com/96751884/147714248-c491a080-1ec9-4239-a1d6-dae52febfd7c.png)

**Comment by tomwolfgang** [comment]
@starmun-0010 we figured it out - the zip file contains two entries for the same file - causing CF to fail unzipping it
![image](https://user-images.githubusercontent.com/1466106/147753148-dfd589de-5d6b-427f-b2f6-49fcee8768ce.png)

We ended up unzipping it locally, rezipping and importing it

**Comment by starmun-0010** [comment]
oh wow, I'll promptly fix that.
@tomwolfgang  Did you figure out why it was happening randomly and wasn't a universal issue for everyone trying to install?
Also, as it seems that currse client cannot handle case sensitiveness. It may be useful to implement a fix or at least a better error.

**Comment by starmun-0010** [comment]
@jiljoel Can you please let me know if you are able to install the version 0.1.8a?

**Comment by tomwolfgang** [comment]
@starmun-0010 no - we are trying to reproduce it with that file.
We'll look at failing such uploads in the future.

Thanks for fixing it!

**Comment by jiljoel** [comment]
Hello,

I Tried with the 0.1.8a file and the install worked perfectly. 

Thanks to everybuddy who helped :)
