### ISSUE TITLE
Mining Fatigue issue 

### ISSUE THREAD

**Issue by krycul19** [AbdulMuqsit/Starpack-Aleph#126]
Shortly after logging in and playing i get a permanent mining fatigue debuff (level 1).  I can't seem to pinpoint whether it is due to combat or not as seems to appear shortly after log in.

**Modpack Version**
- [ ] Aleph
- [x ] Titan

**To Reproduce**
Cant seem to reproduce with any concise controls.  I have created several worlds and in each I get it about 5 or 10 mins after login.  I have managed to drink buckets of milk with no effect.  I also created a new world with cheats on to use /effect clear command and that did not remove it either.

**Expected behavior**
I am sure there is a mod that is causing this -- but the sheer number of mods is making this hard to pinpoint.  I thought it might have been Nutrition related -- but that specific mod is not in this pack.  There might be others that act like it -- but are not obvious to me.  I checked out Spice of Life and farmers delight --- but neither have pointed out anything.

It seems to be related to either combat and/or eating food.  If I just sit around in my base and do nothing -- nothing appears.  If I engage in combat and lose health I notice when combat is over -- that the debuff is there.

**Comment by krycul19** [comment]
well -- I did some more testing. I don't believe this is hunger related.  I sprinted all around my base until my hunger was depleted and waited.  no debuff.  But as soon as I entered combat I got the debuff.  Just fighting zombies, skellies, and spiders in a dungeon tower nearby.  This debuff only appears after being in combat.  It only goes away if I log out.

**Comment by Chaest** [comment]
Issue still there. Apparently the debuff appears as soon as one receives damages. Only way to get rid of it is to log out or to die.

**Comment by starmun-0010** [comment]
Fixed in 0.1.9
