### ISSUE TITLE
Nether Crash

### ISSUE THREAD

**Issue by DurzaDawnstrider** [AbdulMuqsit/Starpack-Aleph#38]
Each time I go into the nether on the server, it times me out, then crashes the server

**Comment by starmun-0010** [comment]
It randomly deadlocks in random worlds. Thanks for informing, I am looking into the crash.
[crash-2021-03-12_16.26.59-server.txt](https://github.com/AbdulMuqsit/Starpack-Aleph/files/6132916/crash-2021-03-12_16.26.59-server.txt)

**Comment by starmun-0010** [comment]
Fixed with #40
