### ISSUE TITLE
Mana-and-Artifice Overrides Librarian Villager trades

### ISSUE THREAD

**Issue by DurzaDawnstrider** [AbdulMuqsit/Starpack-Aleph#83]
A config option in Mana and Artifice causes all Librarian villagers to have the same trades

**Comment by starmun-0010** [comment]
Requires further information.

I could only find the following config option. 
Provide details on what it is you want to be changed.
![image](https://user-images.githubusercontent.com/5557278/113420043-0c1c3800-93e2-11eb-8174-d6915966cdb0.png)
