### ISSUE TITLE
Villagers not accepting the Fletching Table

### ISSUE THREAD

**Issue by DurzaDawnstrider** [AbdulMuqsit/Starpack-Aleph#84]
Title, but it is a known issue with the Apotheosis Village Module

**Comment by starmun-0010** [comment]
There hasn't been any fix released by the mod authors.
Only thing I can do to temporarily fix this is disable the villagers module entirely.

**Comment by starmun-0010** [comment]
![image](https://user-images.githubusercontent.com/5557278/113421810-21469600-93e5-11eb-8d58-74a84dee4c77.png)

**Comment by starmun-0010** [comment]
The fletching table issue is fixed in the latest apotheosis release.
Update mod and re-enable villagers module.
